module.exports = {
    mode: 'jit',
    content: [
        './*/*.php',
        './**/*.php',
        './assets/css/*.css',
        './resources/js/*.js',
    ],
    corePlugins: {
      // ...
     container: false,
    },
    theme: {
        // All rem values x1.6 to compensate for html { font-size: 62.5% }
        fontSize: {
            'xs': '1.2rem',
            'sm': '1.4rem',
            'tiny': '1.4rem',
            'base': '1.6rem',
            'md': '1.6rem',
            'lg': '1.8rem',
            'xl': '2rem',
            '1xl': '2.16rem',
            '2xl': '2.4rem',
            '3xl': '3rem',
            '4xl': '3.6rem',
            '5xl': '4rem',
            '6xl': '4.8rem',
            '7xl': '8rem',
        },
        spacing: {
            'px': '1px',
            '0': '0',
            '0.5': '0.2rem',
            '1': '0.4rem',
            '1.5': '0.6rem',
            '2': '0.8rem',
            '2.5': '1rem',
            '3': '1.2rem',
            '3.5': '1.4rem',
            '4': '1.6rem',
            '5': '2rem',
            '6': '2.4rem',
            '7': '2.8rem',
            '8': '3.2rem',
            '9': '3.6rem',
            '10': '4rem',
            '11': '4.4rem',
            '12': '4.8rem',
            '14': '5.6rem',
            '16': '6.4rem',
            '20': '8rem',
            '24': '9.6rem',
            '28': '11.2rem',
            '32': '12.8rem',
            '36': '14.4rem',
            '40': '16rem',
            '44': '17.6rem',
            '48': '19.2rem',
            '52': '20.8rem',
            '56': '22.4rem',
            '60': '24rem',
            '64': '25.6rem',
            '72': '28.8rem',
            '80': '32rem',
            '96': '38.4rem',
        },
        fontFamily: {
            'sans': ['Lato', 'system-ui'],
            'serif': ['Georgia', 'serif'],
            'heading': ['MonumentGrotesk', 'system-ui'],
            'body': ['Lato'],
        },
        borderRadius: {
            'none': '0',
            'sm': '0.2rem',
            'DEFAULT': '0.4rem',
            'md': '0.6rem',
            'lg': '0.8rem',
            'xl': '1.2rem',
            '2xl': '1.6rem',
            '3xl': '2.4rem',
            'full': '9999px',
        },
        lineHeight: {
            'none': '1',
            'tight': '1.25',
            'snug': '1.375',
            'normal': '1.5',
            'relaxed': '1.625',
            'loose': '2',
            '3': '1.2rem',
            '4': '1.6rem',
            '5': '2rem',
            '6': '2.4rem',
            '7': '2.8rem',
            '8': '3.2rem',
            '9': '3.6rem',
            '10': '4rem',
        },
        extend: {
            colors: {
                'festival-black': '#ffffff',
                'festival-gold': '#C8A84E',
                'festival-gray': '#9CA3AF',
                'festival-light': '#1f1f1f',
                'festival-border': '#ffffff',
            },
            maxWidth: {
                'content': '1440px',
                '3xl': '768px',
                '4xl': '896px',
            },
            screens: {
                'xl': '1200px',
            },
        },
    },
    plugins: [],
}
